MaxHistoryInMemory: 10
HTTPPort: 3000
HTTPHost: "0.0.0.0"
Gotify:
  GotifyURL:        "http://gotify"
  ApplicationToken: "A7vpbrHJmqJe5ew"
Targets:
- Name:                  "Test"
  ConnectionInformation: "https://www.pjotrs.nl"
  Checks:
  - Name:     "httpupcheck"
    Schedule: "*/10 * * * * *"
    Options:
      timeoutInSeconds: "3"
    DisableGotifyForSuccessfulCheck: false
  - Name:     "runcmdcheck"
    Schedule: "*/5 * * * * *"
    Options:
      cmd: "ping -c 1 127.0.0.1"
      printoutput: "false"
