version: "3.9"
services:
  gomonitoring:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./example/exampledockercompose.yaml:/data/config.yaml
    environment:
      CONFIG_PATH: "/data/config.yaml"
  gotify:
    image: ghcr.io/gotify/server
    ports:
      - "8080:80"
    # volumes:
    #   - /var/gotify/data:/app/data
    environment:
      TZ: "Europe/Berlin"
      GOTIFY_DEFAULTUSER_PASS: "custom"