swagger: "2.0"
info:
  title: Go monitoring
  version: 1.0.0
paths:
  /check:
    get:
      summary: List all checks
      operationId: listAllChecks
      responses:
        200:
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/Check'
  /check/{targetName}/{checkName}:
    get:
      summary: Get historical data of a check
      operationId: getTargetChecks
      parameters:
        - name: targetName
          in: path
          description: Name of the target
          required: true
          type: string
        - name: checkName
          in: path
          description: Name of the check
          required: true
          type: string
      responses:
        '200':
          description: Successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/CheckResult'
definitions:
  Check:
    required:
      - TargetName
      - CheckName
      - Schedule
      - LastCheckResult
    properties:
      TargetName:
        type: string
      CheckName:
        type: string
      Schedule:
        type: string
      LastCheckResult:
        $ref: '#/definitions/CheckResult'
  CheckResult:
    required:
      - Error
      - Success
      - LastCheck
      - Message
    properties:
      Error:
        type: string
      Success:
        type: boolean
      LastCheck:
        type: string
      Message:
        type: string
