// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pjotrscholtze/go-monitoring/models"
)

// GetTargetChecksOKCode is the HTTP code returned for type GetTargetChecksOK
const GetTargetChecksOKCode int = 200

/*GetTargetChecksOK Successful operation

swagger:response getTargetChecksOK
*/
type GetTargetChecksOK struct {

	/*
	  In: Body
	*/
	Payload []*models.CheckResult `json:"body,omitempty"`
}

// NewGetTargetChecksOK creates GetTargetChecksOK with default headers values
func NewGetTargetChecksOK() *GetTargetChecksOK {

	return &GetTargetChecksOK{}
}

// WithPayload adds the payload to the get target checks o k response
func (o *GetTargetChecksOK) WithPayload(payload []*models.CheckResult) *GetTargetChecksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get target checks o k response
func (o *GetTargetChecksOK) SetPayload(payload []*models.CheckResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTargetChecksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.CheckResult, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
